### ISSUE TITLE
Бот перестает реагировать

### ISSUE THREAD

**Issue by freefelt** [nerzh/swift-telegram-sdk#22]
Привет! Есть ли у бота какой-то таймаут? Такое чувство, что, если не пользоваться им 3-4 часа, он просто перестает реагировать. Причем в консоль ничего не выводится, процесс Vapor запущен и работает, а бот не отвечает. Делал на основе примера.

**Comment by freefelt** [comment]
Вот прям сейчас проект запущен в Xcode. Последний раз в боту было обращение 3.5 часа назад (я на каждую функцию повесил лог, чтобы понять что происходит перед зависанием). Проект выполняется, но бот ни на что не реагирует. http://127.0.0.1:8080 отвечает. Инициализация бота ровно такая же, как и в примере. Я только токен указал.

**Comment by nerzh** [comment]
в примере используется лонгполлинг, это вообще далеко от слова продакшн, надо использовать вебхук, но впрочем и лонгполлинг не должен зависать. Единственное, что хочу отметить, на вебхуке не только у меня, но и у комьюнити реализованы боты, работают долго, и даже с платежами. В описании есть чат в телеграм, задайте свой вопрос там

**Comment by freefelt** [comment]
Спасибо! Как снова зависнет, я попробую проверить продолжается ли вызываться ли getUpdates() у connection. Я правильно понимаю, что если он перестает вызываться, то еще раз connection.start() может помочь?

**Comment by ct4h** [comment]
Ошибка внутри таски лонг пуллинг, на веб хуке аналогично. Если в getUpdates произойдет ошибка, тогда все останавливается 

````
        Task.detached { [weak self] in
            guard let self = self else { return }
            
            while !Task.isCancelled {
                try await Task.sleep(nanoseconds: 100)
                try await self.getUpdates()
            }
        }
````

Содержимое обернул в do/catch и в случае ошибки выполняю рестарт

**Comment by freefelt** [comment]
Спасибо! А можно попросить сам код, где и как ты делаешь рестар, пожалуйста?

**Comment by freefelt** [comment]
Нашел в твоем форке, видимо оно. Спасибо большое)

**Comment by ct4h** [comment]
@nerzh идея с рестартом провалилась, как только перестал наблюдать за ботом, он перестал реагировать на команды) 

обратил внимание, что после каждого запроса увеличивает переменную offset, может упираемся в предел?

Пока склоняюсь к варианту - с помощью https://github.com/vapor/queues-redis-driver.git , раз в час пересоздавать LongPollingConnection

**Comment by nerzh** [comment]
@ct4h обновил библиотеку до мажорной версии. Логика вынесена, а пример сетевого слоя для вапора все там же в папке -example . Тоесть можно реализовать протокол клиента и использовать с другим фреймворком. 

Изменения не сильно но ломающие, логика хендлеров такая же, изменена только начальная конфигурация. Можете попробовать проверить решилась ли проблема, но я так же просто делаю переподключение при ошибке. И не забывайте выставлять уровень логов debug. А в остальном, используйте лучше webhook

**Comment by nerzh** [comment]
Все пользователи библиотеки все больше склоняются к тому. что это блокировка со стороны telegram. Для этого в инициализаторе TGBot появилось ограничение запросов в секунду для лонгполлинга и для вебхука попробуйти их
