### ISSUE TITLE
Предупреждения в файле TelegramController.swift

### ISSUE THREAD

**Issue by Cyero** [nerzh/swift-telegram-sdk#23]
Постоянно в Xcode висят предупреждения:
1. "Converting non-sendable function value to '@Sendable (Request) async throws -> Bool' may introduce data races".
2. "Non-sendable type 'any TGConnectionPrtcl' in implicitly asynchronous access to actor-isolated property 'connection' cannot cross actor boundary" - исправляеься заменой "import TelegramVaporBot" на "@preconcurrency import TelegramVaporBot" 
Xcode v.15.3, Swift v.5.10

**Comment by nerzh** [comment]
спсб за репорт, покажите пжлст скрин на какой строке ругается или немного подробнее, чтоб было быстрее

**Comment by Cyero** [comment]
> спсб за репорт, покажите пжлст скрин на какой строке ругается или немного подробнее, чтоб было быстрее

<img width="691" alt="Снимок экрана 2024-04-12 в 18 34 25" src="https://github.com/nerzh/telegram-vapor-bot/assets/17139096/cd35677d-eaf9-4330-b5d6-cf462183993c">

Также заметил такое-же поведение в файле config.swift

<img width="923" alt="Снимок экрана 2024-04-12 в 18 35 45" src="https://github.com/nerzh/telegram-vapor-bot/assets/17139096/1c61fca7-5fb7-406e-af3c-3f4bee9c2b94">

**Comment by nerzh** [comment]
Странно, но я этих предупреждений не получал. Сейчас библиотеку обновил, теперь она отвязана от Vapor, немного упрощена инициализация самого бота и есть много примеров бота с использованием других фреймворков. Возможно ваша проблема так же была решена. Если нет, то откройте этот вопрос снова.
