### ISSUE TITLE
`createChatInviteLink` shouldn't return `Bool`

### ISSUE THREAD

**Issue by MihaelIsaev** [nerzh/swift-telegram-sdk#32]
Hey @nerzh 

First of all thanks for your great library!

I realized that `createChatInviteLink ` should return `TGChatInviteLink` instead of `Bool`

https://github.com/nerzh/swift-telegram-sdk/blob/8fd55946e455e28f2b8f3d1ab2920aa080219c89/Sources/SwiftTelegramSdk/Bot/Telegram/Methods/CreateChatInviteLink.swift#L61

**Comment by nerzh** [comment]
thank you very much, fixed 3.4.1
