### ISSUE TITLE
Run on external device

### ISSUE THREAD

**Issue by NikKovIos** [nerzh/swift-telegram-sdk#33]
Hello, I'm sorry for the possibly stupid question. 

I found how to launch a bot by building via xcode. But I don't quite understand how to run it on a remote machine, on a hosting? If anyone has any experience, please share how you run the bot.

**Comment by nerzh** [comment]
Compile your bot and run the binary. In the simplest variant use longpolling. But it is a bit slower than webhooks and there are cases when the bot stops responding. 

If you want to use webhooks, you need an https certificate for the domain and you also need a domain for the bot. Configure nginx etc. What will be difficult to describe here, it is better to try to ask in the telegram chat which is specified in the readmi

**Comment by NikKovIos** [comment]
Thank you for answer. Can you please explain how to make a binary and run it on mac that don't have xcode? Now I can only run bot via xcode.

**Comment by NikKovIos** [comment]
I've found something like instruction https://biser.medium.com/how-to-create-a-telegram-bot-with-swift-using-vapor-d302d27b4844

**Comment by NikKovIos** [comment]
It seems I need to 

1) Install swift
2) `swift build`
3) `swift run`
