### ISSUE TITLE
https://docs.python-telegram-bot.org/en/v13.15/telegram.ext.conversationhandler.html

### ISSUE THREAD

**Issue by NikKovIos** [nerzh/swift-telegram-sdk#34]
https://docs.python-telegram-bot.org/en/v13.15/telegram.ext.conversationhandler.html
https://stackoverflow.com/q/68142791/5790492
https://stackoverflow.com/questions/68142791/how-to-get-several-inputs-in-one-command-in-telegram-bot-api

Does it has a support for conversationhandler or would have it in future?)

**Comment by nerzh** [comment]
you send documentation for python telegram bot. In the description of my library it is said that I do not enter any of my own DSL to implement logic. This library implements all methods according to the OFFICIAL api telegram bot api [core.telegram.org/bots/api#available-methods](https://core.telegram.org/bots/api#available-methods). You can implement all other logic of your application as you like, you are not limited by anything.

**Comment by nerzh** [comment]
This library supports ALL methods from the official Telegram bot API.

**Comment by NikKovIos** [comment]
Thanks for your answer 🙏🏻 

Maybe you can help with advice about how to achieve question-answer behaviour like described in https://stackoverflow.com/questions/68142791/how-to-get-several-inputs-in-one-command-in-telegram-bot-api?

**Comment by nerzh** [comment]
Вы получаете все, что Telegram отправляет вам в обновлении, вы можете посмотреть Xcode, чтобы увидеть, из чего состоит этот тип данных, вы разработчик Swift, а Swift — это скомпилированный язык, который позволяет вам успешно проверять любой класс. Или вы можете обратиться к официальной документации https://core.telegram.org/bots/api#getting-updates

затем получить текст или что-то еще, что вас интересует, и выполнить любую необходимую логику, включая, если необходимо, реакцию с ответом пользователю.

в примерах есть несколько вариантов, запустите их и посмотрите, что произойдет, поставьте отпечатки, чтобы понять, что приходит.

https://github.com/nerzh/swift-telegram-sdk/blob/master/Examples/Vapor-Telegram-Bot/Sources/Vapor-Telegram-Bot/TGBot/TGHandlers/DefaultBotHandlers.swift#L23

**Comment by nerzh** [comment]
I don't understand why you are asking this here and not in the server swift chat in telegram that I told you about?

**Comment by NikKovIos** [comment]
Thank you for your answers and time. This is a great project!
