### ISSUE TITLE
Не могу настроить Webhooks

### ISSUE THREAD

**Issue by ooleynich** [nerzh/swift-telegram-sdk#35]
Сделал все как в readme файле(и в примере https://github.com/nerzh/swift-telegram-sdk/tree/master/Examples/Vapor-Telegram-Bot)
Настроил webhooks верно: 
1) Запрос https://api.telegram.org/bot{...}/getWebhookInfo показывет корректный url
2) В консоли XCode вижу приходящие запросы при общении с ботом в ТГ

Но почему-то запросы не доходят до бота.
В режиме longpolling все работает отлично

В первоначальной библиотеке(https://github.com/givip/Telegrammer) была еще такая строчка:
"app.middleware.use(myBot)"
Может и тут я что-то упускаю, и приложение просто "не знает", что нужно "перенаправить" запросы в бота?

**Comment by nerzh** [comment]
в консоли XCode вебхуки работать не будут, чтобы они работали нужен домен и SSL сертификат, тоесть https

**Comment by nerzh** [comment]
также обратите внимание на телеграм чат ServerSideSwift в ридми, там больше людей меньше задержка ответа и много людей кто использует эту библиотеку и имеет с ней опыт не первый год

**Comment by ooleynich** [comment]
Спасибо за ссылку на чат, подал запрос
А по моему вопросу, наверное, я неверно сформулировал, дополню:
я сделал туннель через xTunnel/ngrok, настроил webhooks, как в readme/примере, и получаю запросы от телеграма - вижу их в Vapor хэндлерах: добавляю route "app.post { req async in ... }" и в нем вижу эти запросы, вот прямо все данные в теле JSON(update_id, от кого, callback_data, text, ...).
Но до самой либы бота они не доходят - не вызываются хэндлеры именно в боте :-(

**Comment by ooleynich** [comment]
Покопался в Ваших примерах, нашел, чего не хватает: настроить routes, теперь заработало 😆
PS Добавьте этот пункт настройки в readme, думаю, будет не лишним

**Comment by nerzh** [comment]
добавил описание в ридми, спасибо
